-- Drop existing company functions before recreating them
-- This ensures functions are recreated with correct signatures

DROP FUNCTION IF EXISTS company_get_by_id(INTEGER);
DROP FUNCTION IF EXISTS company_get_by_email(VARCHAR);
DROP FUNCTION IF EXISTS company_get_by_verification_token(VARCHAR);
DROP FUNCTION IF EXISTS company_create(VARCHAR, VARCHAR, TIMESTAMP, TIMESTAMP, VARCHAR, TIMESTAMP, VARCHAR, TIMESTAMP, TIMESTAMP);
DROP FUNCTION IF EXISTS company_create(VARCHAR, VARCHAR, TIMESTAMPTZ, TIMESTAMPTZ, VARCHAR, TIMESTAMPTZ, VARCHAR, TIMESTAMPTZ, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS company_update(INTEGER, VARCHAR, VARCHAR, TIMESTAMP, TIMESTAMP, VARCHAR, TIMESTAMP, VARCHAR, TIMESTAMP);
DROP FUNCTION IF EXISTS company_update(INTEGER, VARCHAR, VARCHAR, TIMESTAMPTZ, TIMESTAMPTZ, VARCHAR, TIMESTAMPTZ, VARCHAR, TIMESTAMPTZ);

SELECT 'Old company functions dropped successfully!' AS status;
